Asignacion3
fabriales14/AkureyTraining pull request #3
Opened 2019-04-16 20:25 UTC by fabriales14

Asignación 3:
Reproducir el siguiente [website](https://drive.google.com/file/d/1KBDJMJBGikbPbCw7hFnZrS5b70mY8plD/view) utilizando el boilerplate de la empresa
Utilice este proyecto en [Figma](https://www.figma.com/files/recent) para obtener las medidas y assets del sitio web
El sitio debe ser Mobile-First
Los assets los puede encontrar en el siguiente enlace
No utilice librerías como Bootstrap, Material, ... 
Utilice BEM
Utilice flex-box para reducir el tiempo de desarrollo
Los colores y fuentes no pueden cambiar**
El sitio tiene que ser funcional para Chrome, Firefox e IE (version 9.0)

2019-04-26 22:04 UTC, jaalvarezg92 commented on Run Forest, Run!/index.html
> +                        <h1 class="container__item__header__tittle">{{title}}</h1>
typo here `tittle` -> `title`

2019-04-26 22:07 UTC, jaalvarezg92 requested changes

2019-04-26 22:07 UTC, jaalvarezg92 commented on Run Forest, Run!/scss/partials/_base.scss
> +
Remove this empty line

2019-04-26 22:07 UTC, jaalvarezg92 commented on Run Forest, Run!/scss/partials/_content.scss
> +
Remove empty line

2019-04-26 22:07 UTC, jaalvarezg92 commented on Run Forest, Run!/scss/partials/_general.scss
> +
Remove all these empty lines

2019-04-29 17:15 UTC, fabriales14 commented
Thanks! I added the final changes.

2019-04-29 17:15 UTC, merged